tus:
  server:
    data:
      directory: "D:"
      expiration: 3600000

spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  application:
    name: tus
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    tags:
      application: ${spring.application.name}